# ==============================================================================
# Script Name: 04_deseq2_analysis.R
#
# Description:
#   This script performs Differential Expression Analysis (DEA) using the DESeq2 
#   package. It takes the raw count matrix generated by featureCounts as input, 
#   normalizes the data, calculates fold changes and p-values, and identifies 
#   significantly differentially expressed genes (DEGs).
#   
#   It also automatically generates key quality control and result visualizations:
#   1. PCA Plot: To check sample clustering and batch effects.
#   2. Volcano Plot: A global view of significantly up/down-regulated genes.
#   3. Heatmap: Hierarchical clustering of the top significant genes.
#
# Inputs:
#   - A raw count matrix file (e.g., counts.txt from step 03).
#
# Outputs:
#   - A CSV file containing all differential expression results.
#   - A CSV file containing only the significant DEGs.
#   - High-resolution PDF plots (PCA, Volcano, Heatmap) in the results directory.
#
# Usage:
#   1. Modify the parameters in the "USER CONFIGURATION" section below.
#   2. Run the script: Rscript scripts/04_deseq2_analysis.R
# ==============================================================================

# --- USER CONFIGURATION START: Modify these parameters for your specific data ---
COUNTS_FILE <- "./results/quantification/counts.txt"
OUTPUT_DIR <- "./results/deseq2"

# Define your sample groups. The length of this vector MUST match the number of 
# samples (BAM files) in your count matrix. 
# Example: 3 controls and 3 treatments.
SAMPLE_CONDITIONS <- c("Control", "Control", "Control", "Treatment", "Treatment", "Treatment")

P_ADJ_CUTOFF <- 0.05
LOG2FC_CUTOFF <- 1
# --- USER CONFIGURATION END ---

# Create output directory
if (!dir.exists(OUTPUT_DIR)) {
  dir.create(OUTPUT_DIR, recursive = TRUE)
}

suppressPackageStartupMessages({
  library(DESeq2)
  library(ggplot2)
  library(EnhancedVolcano)
  library(pheatmap)
})

cat("-> Loading count matrix...\n")
counts <- read.table(COUNTS_FILE, header = TRUE, row.names = 1)

# featureCounts outputs annotation columns (Chr, Start, End, Strand, Length) in cols 1-5.
# We must remove them to keep only the sample count data.
counts <- counts[, -c(1:5)] 

sample_info <- data.frame(
  condition = factor(SAMPLE_CONDITIONS),
  row.names = colnames(counts)
)

cat("-> Constructing DESeqDataSet...\n")
dds <- DESeqDataSetFromMatrix(countData = counts,
                              colData = sample_info,
                              design = ~ condition)

cat("-> Running DESeq2 pipeline...\n")
dds <- DESeq(dds)
res <- results(dds)

# Export raw results
write.csv(as.data.frame(res), file = file.path(OUTPUT_DIR, "all_results.csv"))

cat("-> Extracting significant DEGs...\n")
res_sig <- subset(res, padj < P_ADJ_CUTOFF & abs(log2FoldChange) > LOG2FC_CUTOFF)
write.csv(as.data.frame(res_sig), file = file.path(OUTPUT_DIR, "significant_DEGs.csv"))

cat("-> Generating plots...\n")

# 1. PCA Plot
vsd <- vst(dds, blind = FALSE)
pca_plot <- plotPCA(vsd, intgroup = "condition") +
  theme_bw() +
  ggtitle("PCA Plot") +
  theme(plot.title = element_text(hjust = 0.5))

pdf(file.path(OUTPUT_DIR, "PCA_plot.pdf"), width = 7, height = 5)
print(pca_plot)
dev.off()

# 2. Volcano Plot
pdf(file.path(OUTPUT_DIR, "Volcano_plot.pdf"), width = 8, height = 8)
volcano_plot <- EnhancedVolcano(res,
                                lab = rownames(res),
                                x = 'log2FoldChange',
                                y = 'padj',
                                pCutoff = P_ADJ_CUTOFF,
                                FCcutoff = LOG2FC_CUTOFF,
                                pointSize = 2.0,
                                labSize = 4.0,
                                colAlpha = 0.6,
                                legendPosition = 'right',
                                title = "Volcano Plot of DEGs",
                                subtitle = "")
print(volcano_plot)
dev.off()

# 3. Heatmap of Top DEGs
top_genes <- rownames(res_sig)

if (length(top_genes) > 0) {
  # If there are too many significant genes, we limit to the top 50 by padj for a cleaner heatmap
  if (length(top_genes) > 50) {
    res_sorted <- res[order(res$padj), ]
    top_genes <- rownames(res_sorted)[1:50]
  }
  
  mat <- assay(vsd)[top_genes, ]
  mat <- mat - rowMeans(mat) # Center the data
  
  anno_col <- as.data.frame(colData(vsd)[, "condition", drop = FALSE])
  
  pdf(file.path(OUTPUT_DIR, "Heatmap_top_DEGs.pdf"), width = 7, height = 7)
  pheatmap(mat,
           scale = "row",
           annotation_col = anno_col,
           cluster_rows = TRUE,
           cluster_cols = TRUE,
           show_rownames = TRUE,
           main = "Heatmap of Top DEGs",
           color = colorRampPalette(c("navy", "white", "firebrick3"))(100))
  dev.off()
} else {
  cat("   Warning: No significant DEGs found based on current cutoffs. Heatmap skipped.\n")
}

cat("=== DESeq2 Analysis Completed! Results saved in", OUTPUT_DIR, "===\n")
