# ==============================================================================
# Script Name: 05_enrichment.R
#
# Description:
#   This script performs Functional Enrichment Analysis to interpret the 
#   biological meaning of the Differentially Expressed Genes (DEGs) identified 
#   in the previous step.
#   
#   It executes the following main tasks:
#   1. Gene ID Conversion: Converts Gene Symbols to Entrez IDs.
#   2. Over-Representation Analysis (ORA): Performs GO (Gene Ontology) and 
#      KEGG pathway enrichment for significant DEGs.
#   3. Gene Set Enrichment Analysis (GSEA): Evaluates coordinate expression 
#      changes across the entire ranked gene list.
#   4. Visualization: Generates dot plots, enrichment maps (emapplot), gene-concept 
#      networks (cnetplot), and GSEA plots.
#
# Inputs:
#   - The 'all_results.csv' file generated by the 04_deseq2_analysis.R script.
#
# Outputs:
#   - CSV tables containing GO, KEGG, and GSEA enrichment results.
#   - PDF plots for ORA and GSEA visualizations.
#
# Usage:
#   1. Modify the parameters in the "USER CONFIGURATION" section below.
#   2. Run the script: Rscript scripts/05_enrichment.R
# ==============================================================================

# --- USER CONFIGURATION START: Modify these parameters for your specific data ---
INPUT_FILE <- "./results/deseq2/all_results.csv"  
OUTPUT_DIR <- "./results/enrichment"             

# Cutoffs used to define significant DEGs for ORA (GO/KEGG)
P_ADJ_CUTOFF <- 0.05
LOG2FC_CUTOFF <- 1

# Database configuration (Default is human: org.Hs.eg.db, 'hsa' for KEGG)
ORGANISM_KEGG <- "hsa"
PATHVIEW_ID <- "hsa04110"  # Specify a KEGG pathway ID to visualize (e.g., Cell cycle)
# --- USER CONFIGURATION END ---

if (!dir.exists(OUTPUT_DIR)) {
  dir.create(OUTPUT_DIR, recursive = TRUE)
}

suppressPackageStartupMessages({
  library(clusterProfiler)
  library(org.Hs.eg.db)
  library(enrichplot)
  library(dplyr)
  library(ggplot2)
  library(pathview)
})

cat("-> Loading DESeq2 results...\n")
res_df <- read.csv(INPUT_FILE, row.names = 1)
res_df$gene_symbol <- rownames(res_df)
res_clean <- na.omit(res_df)

cat("-> Converting Gene Symbols to Entrez IDs...\n")
id_map <- bitr(res_clean$gene_symbol, 
               fromType = "SYMBOL", 
               toType = "ENTREZID", 
               OrgDb = org.Hs.eg.db)

res_with_entrez <- left_join(res_clean, id_map, by = c("gene_symbol" = "SYMBOL"))
res_final <- res_with_entrez[!is.na(res_with_entrez$ENTREZID), ]

gene_list_entrez <- res_final$ENTREZID[abs(res_final$log2FoldChange) > LOG2FC_CUTOFF & res_final$padj < P_ADJ_CUTOFF]

fc <- res_final$log2FoldChange
names(fc) <- res_final$ENTREZID

res_final$rank_metric <- sign(res_final$log2FoldChange) * (-log10(res_final$pvalue))
res_sorted <- res_final[order(-res_final$rank_metric), ]
gene_sorted <- res_sorted$rank_metric
names(gene_sorted) <- res_sorted$ENTREZID

cat("-> Running GO Enrichment Analysis...\n")
ego_bp <- enrichGO(gene = gene_list_entrez,
                   universe = res_final$ENTREZID,
                   OrgDb = org.Hs.eg.db,
                   keyType = "ENTREZID",
                   ont = "BP",
                   pAdjustMethod = "BH",
                   pvalueCutoff = 0.05,
                   qvalueCutoff = 0.05,
                   readable = TRUE)

write.csv(as.data.frame(ego_bp), file.path(OUTPUT_DIR, "GO_BP_results.csv"))

if (nrow(as.data.frame(ego_bp)) > 0) {
  pdf(file.path(OUTPUT_DIR, "GO_Dotplot.pdf"), width = 8, height = 6)
  print(dotplot(ego_bp, showCategory = 15) + ggtitle("GO Biological Process"))
  dev.off()
  
  ego_bp_sim <- pairwise_termsim(ego_bp)
  pdf(file.path(OUTPUT_DIR, "GO_Emapplot.pdf"), width = 10, height = 8)
  print(emapplot(ego_bp_sim, showCategory = 20))
  dev.off()
  
  pdf(file.path(OUTPUT_DIR, "GO_Cnetplot.pdf"), width = 10, height = 8)
  print(cnetplot(ego_bp_sim, categorySize = "pvalue", foldChange = fc, showCategory = 5))
  dev.off()
}

cat("-> Running KEGG Pathway Analysis...\n")
kegg_enrich <- enrichKEGG(gene = gene_list_entrez,
                          universe = res_final$ENTREZID,
                          organism = ORGANISM_KEGG,
                          keyType = 'kegg',
                          pvalueCutoff = 0.05)

write.csv(as.data.frame(kegg_enrich), file.path(OUTPUT_DIR, "KEGG_results.csv"))

if (nrow(as.data.frame(kegg_enrich)) > 0) {
  pdf(file.path(OUTPUT_DIR, "KEGG_Dotplot.pdf"), width = 8, height = 6)
  print(dotplot(kegg_enrich, showCategory = 15) + ggtitle("KEGG Pathway Enrichment"))
  dev.off()
  
  cat("   Generating Pathview map for pathway:", PATHVIEW_ID, "...\n")
  old_wd <- getwd()
  setwd(OUTPUT_DIR)
  tryCatch({
    pathview(gene.data = fc, pathway.id = PATHVIEW_ID, species = ORGANISM_KEGG, limit = list(gene = max(abs(fc))))
  }, error = function(e) { cat("   Pathview visualization skipped or failed.\n") })
  setwd(old_wd)
}

cat("-> Running GSEA (Gene Set Enrichment Analysis)...\n")
gsea_go <- gseGO(geneList = gene_sorted,
                 OrgDb = org.Hs.eg.db,
                 ont = "BP",
                 minGSSize = 10,
                 maxGSSize = 500,
                 pvalueCutoff = 0.05,
                 pAdjustMethod = "BH",
                 verbose = FALSE)

write.csv(as.data.frame(gsea_go), file.path(OUTPUT_DIR, "GSEA_GO_results.csv"))

if (nrow(as.data.frame(gsea_go)) > 0) {
  pdf(file.path(OUTPUT_DIR, "GSEA_Top_Pathway.pdf"), width = 8, height = 6)
  print(gseaplot2(gsea_go, geneSetID = gsea_go$ID[1], pvalue_table = TRUE,
                  title = gsea_go$Description[1]))
  dev.off()
}

cat("=== Enrichment Analysis Completed! Results saved in", OUTPUT_DIR, "===\n")
